# Generated by Django 2.2.1 on 2019-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='images/'),
        ),
    ]
